image: node:alpine

stages:
  - deploy

pages:
  stage: deploy
  only:
    - master
  script:
    - mkdir public
    - cp index.html public
    - cp -r css public/
    - cp -r js public/
    - cp -r images public/
  artifacts:
    paths:
      - public
